#!/usr/bin/env bash
#Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sudo sh -c 'echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver 511249-web-01 	3.85.177.198:80 check\n\tserver 511249-web-02 100.26.18.117:80 check\n" >> /etc/haproxy/haproxy.cfg'
sudo service haproxy restart
